default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dspblueprints_development
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  host:     <%= ENV["PG_HOST"] %>

test:
  <<: *default
  database: dspblueprints_test
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  host:     <%= ENV["PG_HOST"] %>

production:
  <<: *default
  database: dspblueprints_production
  username: dspblueprints
  password: <%= ENV['DSPBLUEPRINTS_DATABASE_PASSWORD'] %>
